language: java
sudo: required
services: mariadb
addons:
  mariadb: '10.0'
script: mvn clean verify
before_install:
- mysql -u root -e "CREATE DATABASE pydb;"
- mysql -u root -e "CREATE DATABASE pyconfig;"
- mysql -u root -e "CREATE USER 'pxuser'@'%' IDENTIFIED BY 'pxuser';"
- mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'pxuser'@'%';"
- mysql -u root -e "CREATE USER 'pxadmin'@'%' IDENTIFIED BY 'pxadmin';"
- mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'pxadmin'@'%';"
- mysql -upxadmin -ppxadmin pyconfig < ispyb-ejb/db/pyconfig.sql
- mysql -upxadmin -ppxadmin pydb < ispyb-ejb/db/pydb.sql
- for entry in ispyb-ejb/db/scripts/ahead/*; do  echo "Running " $entry; mysql -upxadmin
  -ppxadmin pydb < $entry; done
- cd dependencies
- mvn install:install-file -Dfile=securityfilter.jar -DgroupId=securityfilter -DartifactId=securityfilter
  -Dversion=1.0 -Dpackaging=jar
- mvn install:install-file -Dfile=securityaes.jar -DgroupId=securityaes -DartifactId=securityaes
  -Dversion=1.0 -Dpackaging=jar
- mvn install:install-file -Dfile=jhdf.jar -DgroupId=jhdf -DartifactId=jhdf -Dversion=1.0
  -Dpackaging=jar
- mvn install:install-file -Dfile=jhdf5.jar -DgroupId=jhdf5 -DartifactId=jhdf5 -Dversion=1.0
  -Dpackaging=jar
- mvn install:install-file -Dfile=jhdf5obj.jar -DgroupId=jhdf5obj -DartifactId=jhdf5obj
  -Dversion=1.0 -Dpackaging=jar
- mvn install:install-file -Dfile=jhdfobj.jar -DgroupId=jhdfobj -DartifactId=jhdfobj
  -Dversion=1.0 -Dpackaging=jar
- mvn install:install-file -Dfile=Struts-Layout-1.2.jar -DgroupId=struts-layout -DartifactId=struts-layout
  -Dversion=1.2 -Dpackaging=jar
- mvn install:install-file -Dfile=ojdbc6.jar -DgroupId=ojdbc6 -DartifactId=ojdbc6
  -Dversion=1.0 -Dpackaging=jar
- mvn install:install-file -Dfile=ispyb-WSclient-userportal-gen-1.3.jar -DgroupId=ispyb
  -DartifactId=ispyb-WSclient-userportal-gen -Dversion=1.3 -Dpackaging=jar
- cd ..
deploy:
  provider: openshift
  user: antolinos
  password:
    secure: Wg8eGDPY5fjg6GgWlqFXA9s3r7Lt7IA5bgDz1NO4XlfMh1GhOJRo/sOTcq62NbuD8P1pQ6oyW+8Al3j3U9fJHhTw/HtjsSgOO6/aW8Hh9FKiC4wuynh6fKaBQi30liQcj4R37rfzj4iAJx+yeyGOUiyeMq/urzlrjsv7NKHzgbiRh0NtaodOoOwLuTLeDwEqx8PjwMKWMq0vqNimkAd2u73iF5ER6dOdgqYBXhxgvD7x2wgDVmNQZJzm1SQJHJ8DlN+6EE5ZwxZIBDz0c478Nu41HzkX4iF9bKvRKNKoKIe4HfQLJ3KIhC+RTYvpV5kSDDDtMhKNuahbikezFI6eYZ3xLQxb2gtwx3xUHBTsII9RLGv7GMA92j5kztF0VHkKYfwDKG3s012lJiRLMtzIzELsGns9vbXTzxQh90/1dtnnhfut0FM0PqqXAY9nRVzuiFrmUQGODn9g2HbQ+7gHoL+WDP39H/OEZsa3dXMRXf1B0nsEsipu/AfwimlAVzysWH0byK+H6wam4RXUqHAFHFeQbpqRHhJ7YUnBI6x83j0Ih6q4SnKUsxFN4ptGCFcDzY3DrmMghV5pFnzRWClWOb6xg4wIvC5kfaTj03/7NQAqxS+vCTT+uoNCCiT+5ta0+K45j/ZbhG6xxK1b/IN6nRpKZMjYePKXiNGNH8/IUEs=
  app: ISPyB
  domain: ispyb
  on:
    repo: antolinos/ISPyB
    branch: travis
